export const BASE_URL = ''
export const USERS_URL = '/api/users'
export const CATEGORY_URL = '/api/category'
export const PRODUCT_URL = '/api/products'
export const UPLOAD_URL = '/api/upload'
export const REACT_APP_API_URL= 'https://shopsphere-backend-9xia.onrender.com'
